variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_TAG: $DOCKER_REGISTRY:$CI_COMMIT_SHA
  CLAIR_OUTPUT: High

image: docker:latest

stages:
  - testing
  - building
  - deployment

linting:
  image: node:latest
  tags:
    - docker
  stage: testing
  before_script:
    - npm init --yes
    - npm install -g eslint
  script:
    - eslint -c .eslintrc.js server.js

docker-build:
  image: docker:latest
  stage: building
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - echo $DOCKER_REGISTRY
    - echo $AWS_DEFAULT_REGION
    - echo $IMAGE_TAG
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  script:
    - docker build -t sock-shop/front-end .
    - docker tag sock-shop/front-end:latest $DOCKER_REGISTRY:latest
    - docker push $DOCKER_REGISTRY:latest

deployment:
  stage: deployment
  image: alpine/k8s:1.16.15
  tags:
    - docker
  before_script:
    - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name app-first-sec
    - kubectl version
  script:
    - kubectl apply -f sock-shop-duo.yaml -n sock-shop
  when: manual
